 /// \file AHCALRawModuleGlobal.h
/*
 *
 *-------------------------------------------------------------
 * AHCALRawModuleChannel.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef Testbeam_H
#define Testbeam_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** Testbeam class
 */ 
class Testbeam : public DQMAnalysisModule
{
public:
	Testbeam();
	~Testbeam();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:

	// ADC hitmaps
        DQMMonitorElementPtr                        m_pADC_300;
        DQMMonitorElementPtr                        m_pADC_300_memcell;

	// 4 channels info
        DQMMonitorElementPtr                        m_pADC_1;
        DQMMonitorElementPtr                        m_pADC_2;
        DQMMonitorElementPtr                        m_pADC_3;
        DQMMonitorElementPtr                        m_pADC_4;
        DQMMonitorElementPtr                        m_pTDC_1;
        DQMMonitorElementPtr                        m_pTDC_2;
        DQMMonitorElementPtr                        m_pTDC_3;
        DQMMonitorElementPtr                        m_pTDC_4;
	// 4 channels info, memcell x
        DQMMonitorElementPtr                        m_pADC_memcell_1;
        DQMMonitorElementPtr                        m_pADC_memcell_2;
        DQMMonitorElementPtr                        m_pADC_memcell_3;
        DQMMonitorElementPtr                        m_pADC_memcell_4;
        DQMMonitorElementPtr                        m_pTDC_memcell_1;
        DQMMonitorElementPtr                        m_pTDC_memcell_2;
        DQMMonitorElementPtr                        m_pTDC_memcell_3;
        DQMMonitorElementPtr                        m_pTDC_memcell_4;

	// 4 channels memcell
        DQMMonitorElementPtr                        m_pMemCell_1;
        DQMMonitorElementPtr                        m_pMemCell_2;
        DQMMonitorElementPtr                        m_pMemCell_3;
        DQMMonitorElementPtr                        m_pMemCell_4;
 
	bool                                        m_dumpEvent;

	int                                       m_ChipID1;
	int                                       m_ChipID2;
	int                                       m_ChipID3;
	int                                       m_ChipID4;
        int                                       m_ChannelNum1;
        int                                       m_ChannelNum2;
        int                                       m_ChannelNum3;
        int                                       m_ChannelNum4;

        int                                       m_memcell;






}; 

} 

#endif  //  Testbeam_H
