  /// \file AHCALRawModuleChannel.h
/*
 *
 *-------------------------------------------------------------
 * AHCALRawModuleChannel.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef AHCALRAWMODULECHANNEL_H
#define AHCALRAWMODULECHANNEL_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** AHCALRawModuleChannel class
 */ 
class AHCALRawModuleChannel : public DQMAnalysisModule
{
public:
	AHCALRawModuleChannel();
	~AHCALRawModuleChannel();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:

        DQMMonitorElementPtr                        m_pADC_hitbit0_1;
        DQMMonitorElementPtr                        m_pADC_hitbit1_1;
        DQMMonitorElementPtr                        m_pADC_ROC_1;
        DQMMonitorElementPtr                        m_pTDC_ROC_1;
        DQMMonitorElementPtr                        m_pTDC_hitbit0_1;
        DQMMonitorElementPtr                        m_pTDC_hitbit1_1;
        DQMMonitorElementPtr                        m_pWrongBits_1;
        DQMMonitorElementPtr                        m_pADC_WrongBits_1;
        DQMMonitorElementPtr                        m_pTDC_WrongBits_1;

	DQMMonitorElementPtr                        m_pADC_hitbit0_2;
	DQMMonitorElementPtr                        m_pADC_hitbit1_2;
	DQMMonitorElementPtr                        m_pADC_ROC_2;
        DQMMonitorElementPtr                        m_pTDC_ROC_2;
	DQMMonitorElementPtr                        m_pTDC_hitbit0_2;
	DQMMonitorElementPtr                        m_pTDC_hitbit1_2;
	DQMMonitorElementPtr                        m_pWrongBits_2;
        DQMMonitorElementPtr                        m_pADC_WrongBits_2;
        DQMMonitorElementPtr                        m_pTDC_WrongBits_2;

	DQMMonitorElementPtr                        m_pADC_hitbit0_3;
	DQMMonitorElementPtr                        m_pADC_hitbit1_3;
	DQMMonitorElementPtr                        m_pADC_ROC_3;
        DQMMonitorElementPtr                        m_pTDC_ROC_3;
	DQMMonitorElementPtr                        m_pTDC_hitbit0_3;
	DQMMonitorElementPtr                        m_pTDC_hitbit1_3;
	DQMMonitorElementPtr                        m_pWrongBits_3;
        DQMMonitorElementPtr                        m_pADC_WrongBits_3;
        DQMMonitorElementPtr                        m_pTDC_WrongBits_3;

	DQMMonitorElementPtr                        m_pADC_hitbit0_4;
	DQMMonitorElementPtr                        m_pADC_hitbit1_4;
	DQMMonitorElementPtr                        m_pADC_ROC_4;
        DQMMonitorElementPtr                        m_pTDC_ROC_4;
	DQMMonitorElementPtr                        m_pTDC_hitbit0_4;
	DQMMonitorElementPtr                        m_pTDC_hitbit1_4;
	DQMMonitorElementPtr                        m_pWrongBits_4;
        DQMMonitorElementPtr                        m_pADC_WrongBits_4;
        DQMMonitorElementPtr                        m_pTDC_WrongBits_4;

	/* DQMMonitorElement                        *m_pHitsEnergyElement; */
	/* DQMMonitorElement                        *m_pXZProfileElement; */
	/* DQMMonitorElement                        *m_pYZProfileElement; */
	/* DQMMonitorElement                        *m_pXYProfileElement; */
	/* DQMMonitorElement                        *m_pLayerProfileElement; */
	/* DQMMonitorElement                        *m_pTimeElement; */
	/* DQMMonitorElement                        *m_pLastXZProfileElement; */
	/* DQMMonitorElement                        *m_pLastYZProfileElement; */
	/* DQMMonitorElement                        *m_pLastXYProfileElement; */

	bool                                      m_dumpEvent;

        int                                       m_ChipID1;
        int                                       m_ChipID2;
        int                                       m_ChipID3;
        int                                       m_ChipID4;
        int                                       m_ChannelNum1;
        int                                       m_ChannelNum2;
        int                                       m_ChannelNum3;
        int                                       m_ChannelNum4;


}; 

} 

#endif  //  AHCALRAWMODULECHANNEL_H
