  /// \file EUDETtelescopeHotPixels.h
/*
 *
 * EUDETtelescopeHotPixels.h header template automatically generated by a class generator
 * Creation date : tue. sep. 27 2016
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author A. Irles,
 * based on Remi Ete code @copyright CNRS , IPNL
 */


#ifndef EUDETTELESCOPEHOTPIXELS_H
#define EUDETTELESCOPEHOTPIXELS_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** EUDETtelescopeHotPixels class
 */ 
class EUDETtelescopeHotPixels : public DQMAnalysisModule
{
public:
	EUDETtelescopeHotPixels();
	~EUDETtelescopeHotPixels();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:
	DQMMonitorElementPtr                        m_pHotPix1;
	DQMMonitorElementPtr                        m_pHotPix2;
	DQMMonitorElementPtr                        m_pHotPix3;
	DQMMonitorElementPtr                        m_pHotPix4;
	DQMMonitorElementPtr                        m_pHotPix5;
	DQMMonitorElementPtr                        m_pHotPix6;


	bool                                        m_dumpEvent;
	double currentEventNum;
	int **plane_map_array; // store an array representing the map
};

} 

#endif  //  EUDETTELESCOPEHOTPIXELS_H
