  /// \file AHCALRawModuleChannel.h
/*
 *
 *-------------------------------------------------------------
 * AHCALRawModuleChannel.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef TIMECORRELATION_H
#define TIMECORRELATION_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** TimeCorrelation class
 */ 
class TimeCorrelation : public DQMAnalysisModule
{
public:
	TimeCorrelation();
	~TimeCorrelation();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:

       DQMMonitorElementPtr                        m_pTDCvsTime_01_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_02_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_03_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_04_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_05_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_06_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_07_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_08_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_09_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_10_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_11_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_12_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_13_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_14_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_15_a;

	DQMMonitorElementPtr                        m_pTDCvsTime_01_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_02_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_03_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_04_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_05_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_06_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_07_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_08_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_09_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_10_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_11_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_12_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_13_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_14_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_15_b;

	DQMMonitorElementPtr                        m_pTDCvsTime_01_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_02_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_03_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_04_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_05_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_06_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_07_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_08_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_09_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_10_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_11_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_12_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_13_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_14_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_15_c;

        DQMMonitorElementPtr                        m_pTDCvsTime_01_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_02_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_03_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_04_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_05_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_06_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_07_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_08_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_09_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_10_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_11_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_12_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_13_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_14_d;
        DQMMonitorElementPtr                        m_pTDCvsTime_15_d;

	int m_bifoffset;

	bool                                        m_dumpEvent;

}; 

} 

#endif  //  TIMECORRELATION_H
