  /// \file AHCALRawModuleChannel.h
/*
 *
 *-------------------------------------------------------------
 * AHCALRawModuleChannel.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef AHCALRAWMODULEGLOBAL_H
#define AHCALRAWMODULEGLOBAL_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** AHCALRawModuleGlobal class
 */ 
class AHCALRawModuleGlobal : public DQMAnalysisModule
{
public:
	AHCALRawModuleGlobal();
	~AHCALRawModuleGlobal();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:

        DQMMonitorElementPtr                        m_pADC_300;
        DQMMonitorElementPtr                        m_pADC_500;
        DQMMonitorElementPtr                        m_pADC_1000;
        DQMMonitorElementPtr                        m_pADC_1500;
        DQMMonitorElementPtr                        m_pWrongHB;
        DQMMonitorElementPtr                        m_pWrongGB;
        DQMMonitorElementPtr                        m_pWrongBits;

	bool                                        m_dumpEvent;

	int                                         CycleNrIndex;
	int                                         BxIDIndex;
	int                                         EvtNrIndex;
	int                                         ChipIDIndex;
	int                                         NChannelsIndex;
	int                                         TDCFirstChannelIndex;
	int                                         ADCFirstChannelIndex;

	int                                         LDAIndex;
	int                                         portIndex;
	int                                         T1Index;
	int                                         T2Index;
	int                                         T3Index;
	int                                         T4Index;
	int                                         T5Index;
	int                                         T6Index;
	int                                         TDIFIndex;
	int                                         TPWRIndex;

}; 

} 

#endif  //  AHCALRAWMODULEGLOBAL_H
