  /// \file EUDETtelescopeHitMaps.h
/*
 *
 * EUDETtelescopeHitMaps.h header template automatically generated by a class generator
 * Creation date : tue. sep. 27 2016
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author A. Irles,
 * based on Remi Ete code @copyright CNRS , IPNL
 */


#ifndef EUDETTELESCOPEHITMAPS_H
#define EUDETTELESCOPEHITMAPS_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** EUDETtelescopeHitMaps class
 */ 
class EUDETtelescopeHitMaps : public DQMAnalysisModule
{
public:
	EUDETtelescopeHitMaps();
	~EUDETtelescopeHitMaps();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

	StatusCode buildHotPixelsMap(const TiXmlHandle xmlHandle);


protected:
	DQMMonitorElementPtr                        m_pX2;
	DQMMonitorElementPtr                        m_pX3;
	DQMMonitorElementPtr                        m_pX4;
	DQMMonitorElementPtr                        m_pX5;
	DQMMonitorElementPtr                        m_pX6;

	DQMMonitorElementPtr                        m_pY2;
	DQMMonitorElementPtr                        m_pY3;
	DQMMonitorElementPtr                        m_pY4;
	DQMMonitorElementPtr                        m_pY5;
	DQMMonitorElementPtr                        m_pY6;


        std::string                                 m_hotpixelsFilename;

        std::map<int, int>                          hotpixelsmap1;
        std::map<int, int>                          hotpixelsmap2;
        std::map<int, int>                          hotpixelsmap3;
        std::map<int, int>                          hotpixelsmap4;
        std::map<int, int>                          hotpixelsmap5;
        std::map<int, int>                          hotpixelsmap6;
        std::vector<std::map<int, int>>             hotpixelsMap;


	bool                                        m_dumpEvent;
};

} 

#endif  //  EUDETTELESCOPEHITMAPS_H
