
/// \file HitMapTemperatures.cc
/*
 *-------------------------------------------------------------
 * AHCALRawModule.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */


#include "HitMapTemperature.h"
// to handle and acces to the elements in the LCIO generic Object

// -- std headers
#include <ctime>
#include <time.h>
#include <time.h>
#include <locale>
#include <cstdlib>
#include <limits>
#include <string>

//#ifndef USELCIO
//#define USELCIO
#include "EVENT/LCGenericObject.h"
#include "EVENT/LCCollection.h"
#include "EVENT/LCEvent.h"
#include "EVENT/LCIO.h"
#include "UTIL/CellIDDecoder.h"
#include "UTIL/LCTOOLS.h"
//#endif

// -- dqm4hep headers
#include "dqm4hep/DQMMonitorElement.h"
#include "dqm4hep/DQMCoreTool.h"
#include "dqm4hep/DQMRun.h"
#include "dqm4hep/DQMXmlHelper.h"
#include "dqm4hep/DQMEvent.h"
#include "dqm4hep/DQMQualityTest.h"
#include "dqm4hep/DQMModuleApi.h"
#include "dqm4hep/DQMPlugin.h"

// -- root headers
#include "TRandom.h"
#include "TString.h" // Added by Tom for TString handling
#include "TDatime.h"

//using namespace lcio;

namespace dqm4hep
{
  // module plugin declaration
  DQM_PLUGIN_DECL( HitMapTemperature , "HitMapTemperature" )

  //-------------------------------------------------------------------------------------------------

  HitMapTemperature::HitMapTemperature() :
  DQMAnalysisModule()
  {
    setDetectorName("NO DETECTOR");
    setVersion(1, 0, 0);
  }

  //-------------------------------------------------------------------------------------------------

  HitMapTemperature::~HitMapTemperature()
  {
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::readSettings(const TiXmlHandle xmlHandle)
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- readSettings()" );

    std::string m_geometryFilename = "";

    RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, DQMXmlHelper::readParameterValue(xmlHandle,
													     "GeometryFilename", m_geometryFilename));

    dqm4hep::TiXmlDocument m_geometryFile(m_geometryFilename);
    
    if( ! m_geometryFile.LoadFile() )
      return dqm4hep::STATUS_CODE_FAILURE;

    const dqm4hep::TiXmlHandle xmlGeometryFileHandle(&m_geometryFile);

    RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, HitMapTemperature::buildGeometryMap(xmlGeometryFileHandle));

    //----


    //---------------------------------------------------------------------
    //ADC hitmaps
    m_pADC_300_l1 = NULL;
    m_pADC_300_l2 = NULL;
    m_pADC_300_l3 = NULL;
    m_pADC_300_l4 = NULL;
    // m_pADC_300_l5 = NULL;
    // m_pADC_300_l6 = NULL;
    // m_pADC_300_l7 = NULL;
    // m_pADC_300_l8 = NULL;
    // m_pADC_300_l9 = NULL;
    // m_pADC_300_l10 = NULL;
    // m_pADC_300_l11 = NULL;
    // m_pADC_300_l12 = NULL;
    // m_pADC_300_l13 = NULL;
    // m_pADC_300_l14 = NULL;
    // m_pADC_300_l15 = NULL;

    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l1", m_pADC_300_l1));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l2", m_pADC_300_l2));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l3", m_pADC_300_l3));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l4", m_pADC_300_l4));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l5", m_pADC_300_l5));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l6", m_pADC_300_l6));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l7", m_pADC_300_l7));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l8", m_pADC_300_l8));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l9", m_pADC_300_l9));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l10", m_pADC_300_l10));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l11", m_pADC_300_l11));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l12", m_pADC_300_l12));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l13", m_pADC_300_l13));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l14", m_pADC_300_l14));
    // RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "ADC_300_l15", m_pADC_300_l15));

    // TEMPERATURE
    m_pTempAverage_1 = NULL;
    m_pTempAverage_2 = NULL;
    m_pTempAverage_3 = NULL;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempAverage_1", m_pTempAverage_1));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempAverage_2", m_pTempAverage_2));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempAverage_3", m_pTempAverage_3));
    m_pTempDIF_1 = NULL;
    m_pTempDIF_2 = NULL;
    m_pTempDIF_3 = NULL;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempDIF_1", m_pTempDIF_1));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempDIF_2", m_pTempDIF_2));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempDIF_3", m_pTempDIF_3));
    m_pTempPWR_1 = NULL;
    m_pTempPWR_2 = NULL;
    m_pTempPWR_3 = NULL;
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempPWR_1", m_pTempPWR_1));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempPWR_2", m_pTempPWR_2));
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMXmlHelper::bookMonitorElement(this, xmlHandle, "TempPWR_3", m_pTempPWR_3));


    //-----------------------------------------------------
    m_dumpEvent = false;
    RETURN_RESULT_IF_AND_IF(STATUS_CODE_SUCCESS, STATUS_CODE_NOT_FOUND, !=, DQMXmlHelper::readParameterValue(xmlHandle,
													     "DumpEvent", m_dumpEvent));

    return STATUS_CODE_SUCCESS;
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::initModule()
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- init()" );

    // print directory structure of monitor element storage in console
    DQMModuleApi::cd(this);
    DQMModuleApi::ls(this, true);

    return STATUS_CODE_SUCCESS;
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::endModule()
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- end()" );
    return STATUS_CODE_SUCCESS;
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::processEvent(DQMEvent *pEvent)
  {

    int CycleNrIndex = 0;
    int BxIDIndex = 1;
    int EvtNrIndex = 2;
    int ChipIDIndex = 3;
    int NChannelsIndex = 4;
    int TDCFirstChannelIndex = 5;
    int ADCFirstChannelIndex = TDCFirstChannelIndex+36;


    EVENT::LCEvent *pLCEvent = pEvent->getEvent<EVENT::LCEvent>();

    if(!pLCEvent)
      return STATUS_CODE_FAILURE;

    if(m_dumpEvent)
      UTIL::LCTOOLS::dumpEvent(pLCEvent);


    const std::vector<std::string> *pCollectionNames = pLCEvent->getCollectionNames();

    time_t ts =0;
    int timestamp;
    float tdif_1, tdif_2, tdif_3;
    float tpwr_1, tpwr_2, tpwr_3;
    float tav_1, tav_2, tav_3;

    for(std::vector<std::string>::const_iterator colIter = pCollectionNames->begin();
	colIter != pCollectionNames->end() ; ++colIter)
      {

	const std::string &collectionName(*colIter);

	EVENT::LCCollection *pLCCollection = pLCEvent->getCollection(collectionName);


	//----------------------------------
	// temperature section
	if(collectionName=="TempSensor")
	  {

	    const int nElements = pLCCollection->getNumberOfElements();
	    if(nElements !=3) continue;

	    std::string timestamp = pLCCollection->getParameters().getStringVal("Timestamp");
	    struct tm tm;
	    strptime(timestamp.c_str(), "%a, %d %b %Y %H:%M:%S %z", &tm);
	    time_t epoch;
	    epoch = mktime(&tm);
	    
	    //  dt_start = TDatime(timestamp);

	    for(int e=0 ; e<nElements ; e++)
	      {
	    const EVENT::LCGenericObject *const pTempRaw = 
	      dynamic_cast<const EVENT::LCGenericObject *const>(pLCCollection->getElementAt(e));
		
		if(NULL == pTempRaw)
		  continue;
		
		if(e==0) {tdif_1 = pTempRaw->getIntVal(8); tpwr_1 = pTempRaw->getIntVal(9);}
		if(e==1) {tdif_2 = pTempRaw->getIntVal(8); tpwr_2 = pTempRaw->getIntVal(9);}
		if(e==2) {tdif_3 = pTempRaw->getIntVal(8); tpwr_3 = pTempRaw->getIntVal(9);}

		int ntemps=0, tempav=0;
		for(int i=0; i<6; i++) { 
		  if(pTempRaw->getIntVal(2+i) < 1000) {ntemps++; tempav+=pTempRaw->getIntVal(2+i);}  
		}
		tempav=tempav/ntemps;
		if(e==0) tav_1=tempav/10.;
		if(e==1) tav_2=tempav/10.;
		if(e==2) tav_3=tempav/10.;
	      }

	    Int_t pointID = m_pTempAverage_1->get<TGraph>()->GetN();
	    m_pTempAverage_1->get<TGraph>()->SetPoint(pointID, int(epoch), tav_1 );
	    pointID = m_pTempAverage_2->get<TGraph>()->GetN();
	    m_pTempAverage_2->get<TGraph>()->SetPoint(pointID, int(epoch), tav_2 );
	    pointID = m_pTempAverage_3->get<TGraph>()->GetN();
	    m_pTempAverage_3->get<TGraph>()->SetPoint(pointID, int(epoch), tav_3 );

	    pointID = m_pTempDIF_1->get<TGraph>()->GetN();
	    m_pTempDIF_1->get<TGraph>()->SetPoint(pointID, int(epoch), tdif_1 );
	    pointID = m_pTempDIF_2->get<TGraph>()->GetN();
	    m_pTempDIF_2->get<TGraph>()->SetPoint(pointID, int(epoch), tdif_2 );
	    pointID = m_pTempDIF_3->get<TGraph>()->GetN();
	    m_pTempDIF_3->get<TGraph>()->SetPoint(pointID, int(epoch), tdif_3 );

	    pointID = m_pTempPWR_1->get<TGraph>()->GetN();
	    m_pTempPWR_1->get<TGraph>()->SetPoint(pointID, int(epoch), tpwr_1 );
	    pointID = m_pTempPWR_2->get<TGraph>()->GetN();
	    m_pTempPWR_2->get<TGraph>()->SetPoint(pointID, int(epoch), tpwr_2 );
	     pointID = m_pTempPWR_3->get<TGraph>()->GetN();
	    m_pTempPWR_3->get<TGraph>()->SetPoint(pointID, int(epoch), tpwr_3 );

	  }

	//----------------------------------
	// BIF section
	if(collectionName=="EUDAQDataBIF")
	  {
	    


	  }

	//----------------------------------
	// AHCAL section
	if(collectionName=="EUDAQDataScCAL")
	  {

	    if(pLCCollection->getTypeName() == EVENT::LCIO::LCGENERICOBJECT)
	      {

		const int nElements = pLCCollection->getNumberOfElements();
		for(int e=0 ; e<nElements ; e++)
		  {
		    const EVENT::LCGenericObject *const pAHCALRaw = 
		      dynamic_cast<const EVENT::LCGenericObject *const>(pLCCollection->getElementAt(e));

		    if(NULL == pAHCALRaw)
		      continue;

		    const int nChannels = pAHCALRaw->getIntVal(NChannelsIndex);
		    if(nChannels!= 36) {
		      LOG4CXX_INFO( dqmMainLogger , "Wrong number of channels ("<<nChannels<<"), skip event" ); 
		      continue;
		    }

		    for(int f=0 ; f<nChannels ; f++)		// This loop iterates over the channels in each readout cycle
		      {

			// Vectors for storing our TDC and ADC by channel

			int tdcRAW;
			int adcRAW;
			int tdc;
			int adc;
			int hitbit_tdc;
			int gainbit_tdc;
			int hitbit_adc;
			int gainbit_adc;

			tdcRAW = pAHCALRaw->getIntVal(TDCFirstChannelIndex+f);
			adcRAW = pAHCALRaw->getIntVal(ADCFirstChannelIndex+f);

			tdc = tdcRAW%4096;
			adc = adcRAW%4096;

			hitbit_adc = (adcRAW & 0x1000)?1:0;
			gainbit_adc = (adcRAW & 0x2000)?1:0;

			hitbit_tdc = (tdcRAW & 0x1000)?1:0;
			gainbit_tdc = (tdcRAW & 0x2000)?1:0;

			//	std::cout<<m_ChipIDLayer1<<" "<< m_ChipIDLayer2<<" "<<m_ChipIDLayer3<<" "<<m_ChannelNum1<<" "<<m_ChannelNum2<<" "<<m_ChannelNum3<<" "<<m_ChannelNum4<<std::endl;

			if( hitbit_adc != hitbit_tdc || pAHCALRaw->getIntVal(EvtNrIndex) ==0 ) continue;

			if(hitbit_adc != 1) continue;


			int ijk = electronicsToIJK(pAHCALRaw->getIntVal(ChipIDIndex),f);
			int I = ijk / 10000;
			int J = ( ijk  % 10000 ) /100;
			int K = ( ijk  % 10000 ) % 100;

			if(K==4) m_pADC_300_l1->get<TH2I>()->Fill(I,J,adc);
			if(K==4) m_pADC_300_l2->get<TH2I>()->Fill(I,J,adc);
			if(K==4) m_pADC_300_l3->get<TH2I>()->Fill(I,J,adc);
			if(K==4) m_pADC_300_l4->get<TH2I>()->Fill(I,J,adc);



		      }//for f

		  }//for elements

	      }// if LCGENERICOBJECT

	  }//if collectionName == EUDAQDataScCAL
      }// iterator


    return STATUS_CODE_SUCCESS;

  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::startOfCycle()
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- startOfCycle()" );
    return STATUS_CODE_SUCCESS;
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::endOfCycle()
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- endOfCycle()" );

    // run all quality tests on all monitor elements
    RETURN_RESULT_IF(STATUS_CODE_SUCCESS, !=, DQMModuleApi::runQualityTests(this));

    return STATUS_CODE_SUCCESS;
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::startOfRun(DQMRun *pRun)
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- startOfRun()" );
    LOG4CXX_INFO( dqmMainLogger , "Run no " << pRun->getRunNumber() );
    //	time_t startTime = pRun->getStartTime();
    time_t startTime = std::chrono::system_clock::to_time_t(pRun->getStartTime());

    std::string timeStr;
    DQMCoreTool::timeToHMS(startTime, timeStr);

    LOG4CXX_INFO( dqmMainLogger , "Start time " << timeStr );
    LOG4CXX_INFO( dqmMainLogger , "Detector is " << pRun->getDetectorName() );
    LOG4CXX_INFO( dqmMainLogger , "Description " << pRun->getDescription() );

    return STATUS_CODE_SUCCESS;
  }

  //-------------------------------------------------------------------------------------------------

  StatusCode HitMapTemperature::endOfRun(DQMRun *pRun)
  {
    LOG4CXX_INFO( dqmMainLogger , "Module : " << getName() << " -- endOfRun()" );
    LOG4CXX_INFO( dqmMainLogger , "Run no " << pRun->getRunNumber() );

    //	time_t endTime = pRun->getEndTime();
    time_t endTime = std::chrono::system_clock::to_time_t(pRun->getEndTime());
    std::string timeStr;
    DQMCoreTool::timeToHMS(endTime, timeStr);

    LOG4CXX_INFO( dqmMainLogger , "End time " << timeStr );

    return STATUS_CODE_SUCCESS;
  }



  StatusCode HitMapTemperature::buildGeometryMap(const TiXmlHandle xmlHandle)
  {

    LOG4CXX_INFO( dqmMainLogger , "Building geometry map..." );

    //Getting the very first child of the XML file; in our case, this is the dqm4hepGeometryMap bracket.
    const dqm4hep::TiXmlHandle xmlFileHandle(xmlHandle.FirstChildElement().Element());

    //Giving a unique name to the globalGeometryProperties object
    dqm4hep::TiXmlHandle pGlobalPropertiesXmlElement(xmlFileHandle.FirstChild("globalGeometryProperties").Element());

    //Iterate over each layer
    for (dqm4hep::TiXmlElement *pLayerXmlElement = xmlFileHandle.FirstChild("layer").Element(); NULL != pLayerXmlElement; pLayerXmlElement = pLayerXmlElement->NextSiblingElement("layer"))
      {

	dqm4hep::TiXmlHandle pLayerHandle(pLayerXmlElement);

	//Iterate over each chip
	for (dqm4hep::TiXmlElement *pChipXmlElement = pLayerHandle.FirstChild("chip").Element(); NULL != pChipXmlElement; pChipXmlElement = pChipXmlElement->NextSiblingElement("chip"))
	  {

	    dqm4hep::TiXmlHandle pChipHandle(pChipXmlElement);
	
	    //Iterate over each channel
	    for (dqm4hep::TiXmlElement *pChannelXmlElement = pChipHandle.FirstChild("channel").Element(); NULL != pChannelXmlElement; pChannelXmlElement = pChannelXmlElement->NextSiblingElement("channel"))
	      {

		int ChipID, ChannelID, I, J, K, ChpChnNum, ijkNum;

		//Pull out all the data: chip number, channel number, ijk
		pChipXmlElement->QueryValueAttribute<int>("id", &ChipID);
		pChannelXmlElement->QueryValueAttribute<int>("id", &ChannelID);
		pChannelXmlElement->QueryValueAttribute<int>("i", &I);
		pChannelXmlElement->QueryValueAttribute<int>("j", &J);
		pChannelXmlElement->QueryValueAttribute<int>("k", &K);

		//Formatting data to go into our map
		ChpChnNum = ChipID*100+ChannelID;
		ijkNum = I*10000 + J*100 + K;


		//Filling the map (Chip, Chn)->(I, J, K)
		ijkmap.insert(std::make_pair(ChpChnNum, ijkNum));

		//Filling the map (I, J, K)->(Chip, Chn)
		chpchnmap.insert(std::make_pair(ijkNum, ChpChnNum));

	      }
	  }
      }

    std::cout<<chpchnmap.size()<<" "<< ijkmap.size()<<std::endl;

    LOG4CXX_INFO( dqmMainLogger , "Geometry map built successfully." );

    return STATUS_CODE_SUCCESS;

  }

  int HitMapTemperature::electronicsToIJK(int Chip, int Channel)
  {
    std::map<int, int>::iterator itMap;
    int index = Chip*100+Channel;
    int IJK = -1;
    std::cout<<"electronicsToIJK "<<ijkmap.size()<<std::endl;
    std::cout<<index<<" "<<Chip<<" "<<Channel<<std::endl;

    if(ijkmap.find(index) != ijkmap.end())
      {
	itMap = ijkmap.find(index);
	IJK = itMap->second;
	std::cout<<"find: "<<IJK<<std::endl;
      }

    return IJK;
  }

  int HitMapTemperature::IJKToElectronics(int I, int J, int K)
  {
    std::map<int, int>::iterator itMap;
    int index = I*10000+J*100+K;
    int ChipChn= -1;

    if(chpchnmap.find(index) != chpchnmap.end())
      {
	itMap = chpchnmap.find(index);
	ChipChn = itMap->second;
      }

    return ChipChn;
  }

};



