  /// \file AHCALRawModuleChannel.h
/*
 *
 *-------------------------------------------------------------
 * AHCALRawModuleChannel.cc source template automatically modified from 
 * CaloHitModule  generated by a class generator
 * by A. Irles, DESY, 23 March 2016
 *--------------------------------------------------------------
 *
 * This file is part of DQM4HEP libraries.
 * 
 * DQM4HEP is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * DQM4HEP is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with DQM4HEP.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author Remi Ete
 * @copyright CNRS , IPNL
 */

#ifndef TIMECORRELATION_H
#define TIMECORRELATION_H

#include "dqm4hep/DQMAnalysisModule.h"

namespace dqm4hep
{

class DQMMonitorElement;

/** TimeCorrelation class
 */ 
class TimeCorrelation : public DQMAnalysisModule
{
public:
	TimeCorrelation();
	~TimeCorrelation();

	StatusCode initModule();
	StatusCode readSettings(const TiXmlHandle xmlHandle);
	StatusCode processEvent(DQMEvent *pEvent);
	StatusCode startOfCycle();
	StatusCode endOfCycle();
	StatusCode startOfRun(DQMRun *pRun);
	StatusCode endOfRun(DQMRun *pRun);
	StatusCode endModule();

protected:

        DQMMonitorElementPtr                        m_pTDCvsTime_a;
        DQMMonitorElementPtr                        m_pTDCvsTime_b;
        DQMMonitorElementPtr                        m_pTDCvsTime_c;
        DQMMonitorElementPtr                        m_pTDCvsTime_d;

	int m_bifoffset;

	int m_ChannelNr_a;
        int m_ChannelNr_b;
        int m_ChannelNr_c;
        int m_ChannelNr_d;

        int m_ChipNr_a;
        int m_ChipNr_b;
        int m_ChipNr_c;
        int m_ChipNr_d;


	bool                                        m_dumpEvent;

}; 

} 

#endif  //  TIMECORRELATION_H
